events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }

        # عشان الفرونت يكلم الباك إند صح
        location /api/reactions/ {
            proxy_pass http://reactions:8080/;
        }

        location /api/mood/ {
            proxy_pass http://mood:8080/;
        }
    }
}